# 数据库配置
spring:
  # 数据源设定
  datasource:
    # 数据库地址
    # url: jdbc:mysql://127.0.0.1:6666/management?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:postgresql://127.0.0.1:12501/management
    # 账户
    username: postgres
    # 密码
    password: 1192469846
    #    password: 666666
    # 数据库驱动
    driver-class-name: org.postgresql.Driver
    # 指定数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库连接池
    druid:
      # 连接池初始大小
      initial-size: 30
      # 连接池最大上限
      max-active: 100
      # 连接超时时间
      max-wait: 1500

  data:
    redis:
      # redis 服务
      host: 127.0.0.1
      # redis 端口
      port: 12502
      # 密码
      password: 1192469846
      # 默认选择库
      database: 0
      # 使用lettuce整合
      lettuce:
        # 连接池配置
        pool:
          # 最大连接
          max-active: 8
          # 最大闲置
          max-idle: 8
          # 最小闲置
          min-idle: 0
          # 连接超时时间
          max-wait: 1500ms

