# mybatis
#mybatis :
#  configuration :
#    map-underscore-to-camel-case : true

mybatis-plus:
  global-config:
    db-config:
      # 数据库自增策略
      id-type: auto
  configuration:
    # MP标准输出日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.zzk.entity.*
  type-aliases-super-type: java.lang.Object